version: '3.9'

services:

  nginx:
    image: nginx:1.22
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./var/www/media-blob:/var/www/media-blob
      - laravel-project:/var/www/example-app
      # - ./var/www/OEXPOJP-BE:/var/www/OEXPOJP-BE
      - ./nginx/conf.d:/etc/nginx/conf.d

  php:
    # image: php:7.4.30-fpm
    build:
      context: ./php
    ports:
      - 9000:9000
    volumes:
      - ./var/www/OEXPOJP-BE:/var/www/OEXPOJP-BE
      - laravel-project:/var/www/example-app
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   ports:
  #     - 1433:1433
  #   volumes:
  #     - ./mssql/data:/var/opt/mssql/data
  #     - ./mssql/log:/var/opt/mssql/log
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=vJtGZPmO7F77v1M

# 使用 Volumes top-level element 讓 nginx, php service 共享 volume
volumes:
  laravel-project: